### ISSUE TITLE
Issue when adding to composer.

### ISSUE THREAD

**Issue by R-K-H** [seegno/uphold-sdk-php#104]
#: composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package seegno/uphold-sdk-php could not be found in any version, there may ypo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability g
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

I wasn't sure if there was an issue or if the package is available via composer. Thanks!

**Comment by nunorafaelrocha** [comment]
Hi @R-K-H 

The package name was renamed on packagist.org, so this issue seems to be fixed.

Don't forget to clear composer cache as that may be in your way: `composer clear-cache`.

Cheers
