### ISSUE TITLE
FATAL Error 

### ISSUE THREAD

**Issue by ernaneluis** [seegno/uphold-sdk-php#123]
I am getting this error at Mamp  php 5.5.23
PHP Fatal error:  Class 'GuzzleHttp\Message\MessageFactory' not found in ..... /lib/Uphold/HttpClient/Message/MessageFactory.php on line 13

I have tried "composer install -o"   but didn't fix it. Could someone help me out?

**Comment by nunorafaelrocha** [comment]
Hi @ernaneluis,

Can you please paste the composer output?
