### ISSUE TITLE
PHP Fatal error: 

### ISSUE THREAD

**Issue by ernaneluis** [seegno/uphold-sdk-php#124]
I am now getting this: 

PHP Fatal error:  Uncaught exception 'Uphold\Exception\ConnectException' with message 'cURL error 35: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error' in /lib/Uphold/HttpClient/Handler/ErrorHandler.php:49
Stack trace:
#0 lib/Uphold/HttpClient/HttpClient.php(142): Uphold\HttpClient\Handler\ErrorHandler->onException(Object(GuzzleHttp\Exception\ConnectException))
#1 lib/Uphold/HttpClient/HttpClient.php(87): Uphold\HttpClient\HttpClient->request('v0/ticker', NULL, 'GET', Array, Array)
#2 /lib/Uphold/UpholdClient.php(313): Uphold\HttpClient\HttpClient->get('v0/ticker', Array, Array)
#3 /lib/Uphold/UpholdClient.php(152): Uphold\UpholdClient->get('/ticker')
#4 /examples/Ticker.php(11): Uphold\UpholdClient->getRates()
#5 {main}
  th in /lib/Uphold/HttpClient/Handler/ErrorHandler.php on line 49

**Comment by nunorafaelrocha** [comment]
That seems to be a problem with your environment, probably related with your CA root certificate.

I recommend you read this [article](http://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config/) and try to apply the fix suggested there.

Let us know if that work for you!
