### ISSUE TITLE
Bad response from createCard()

### ISSUE THREAD

**Issue by zekylaf** [seegno/uphold-sdk-php#135]
Hi, I do not know why, but I am getting a different response from Uphold.

When I use createCard() method, I get this response:

[{"params":[],"normalized":[{"available":"0.00","balance":"0.00","currency":"USD"}],"wire":[{"accountName":"UPHOLD LDA","address":{"line1":"Rua Tenente Valadim 284","line2":"4100-476 Porto, Portugal"},"currency":"EUR","bic":"BBPIPTPL","iban":"PT50 0010 0000 5108 8690 0026 9","name":"Banco BPI"},{"accountName":"UPHOLD LDA","address":{"line1":"Rua Tenente Valadim 284","line2":"4100-476 Porto, Portugal"},"bic":"BBPIPTPL","currency":"GBP","iban":"PT50 0010 9999 5108 8690 6028 9","name":"Banco BPI"},{"accountName":"Uphold HQ, Inc.","accountNumber":"1463721","address":{"line1":"900 Broad Street","line2":"Newark, NJ 07102"},"bic":"CNNJUS33","currency":"USD","name":"City National Bank of New Jersey"}]}]

What can I do @nunorafaelrocha ? Thanks

**Comment by nunorafaelrocha** [comment]
Hi @zekylaf,

Can you provide the request information?

**Comment by zekylaf** [comment]
Yes. I am using this code:

        
        use Uphold\UpholdClient as Client;

        $usertoken =  'xxxxxxxxxxx'
        $cardcurrency = 'USD';
        $cardname = 'MyNewCard';


        $client = new Client();

        $user = $client->getUser($usertoken);

        $card = $user->createCard($cardname, $cardcurrency);

        return response()->json([$card]);   //(I am using laravel)


I was using that without problem, but one day it stop working. Can you help me please?

**Comment by zekylaf** [comment]
Well, I was reading the Uphold Documentation Api for Curl and I found that now you need to create a new card, get the 'id' of the new card, and then, add a "Crypto Address". You can chose among "bitcoin, litecoin" and others. 

Look at this: https://uphold.com/en/developer/api/documentation/#create-card-crypto-address

I think you will take your time to update your php api, so I think I will use curl. 

Thanks for all!
